### ISSUE TITLE
Code improvement

### ISSUE THREAD

**Issue by opoudjis** [metanorma/omml2mathml#6]
* Code does Iunnecessary marshaling of Nokogiri::XML::Element -> String -> Nokogiri::XML::Document: add each element being converted through XSLT to a dummy document, `doc = Nokogiri::XML::Document::new(); doc.root = x.dup()`
* Instead of hardcoding the target mml namespace and deleting namespaces with gsub, `x.to_xml.sub(/<m:(oMath|oMathPara)>/,"<m:\\1 xmlns:m='http://schemas.openxmlformats.org/officeDocument/2006/math'>")`, use [`add_namespace_definition`](https://www.rubydoc.info/github/sparklemotion/nokogiri/Nokogiri/XML/Node#add_namespace_definition-instance_method)

**Comment by ronaldtse** [comment]
@CAMOBAP795 as mentioned by @opoudjis , would you be able to handle this change? (and have the proper specs to ensure it works) Thanks!

**Comment by CAMOBAP795** [comment]
Reported https://github.com/sparklemotion/nokogiri/issues/1887

**Comment by CAMOBAP795** [comment]
List of open questions:
 - [ ] Find XSD for http://schemas.openxmlformats.org/officeDocument/2006/math
 - [ ] Find XSD for http://schemas.microsoft.com/office/2004/12/omml
 - [ ] Define relationships between two XSDs above
 - [ ] no xmlns:mml defined in output document
 - [ ] no MathML namespace defined in output document
 - [ ] How to test correctness of result doc

**Comment by CAMOBAP795** [comment]
@opoudjis maybe you can share full steps how cam I use `omml2mathml` without metaroma? As far as I understood I need 
 - create docx/doc document with formulas
 - save it as html
 - use this html as input for `omml2mathml` 
 - check that output html is contains MathML only formula 

Right?

**Comment by opoudjis** [comment]
Correct. I created this gem before I found the reverse_markdown gem, which contains a script converting Word DOCX to Markdown, and Word OMML to MathML; I have adapted that script to reverse_asciidoctor/bin/w2a, mapping to Asciidoctor, and that is what we use instead of this gem. It does the DOCX to HTML conversion via LibreOffice, without us having to manually open and save the document. And its HTML to Asciidoctor mapping is somewhat more reliable than what comes out manually, because it uses a LibreOffice XSLT transform.

This gem is here in case anyone needs a standalone converter from Word HTML to DOCX, and it would indeed be used the way you suggest. But we are unlikely to use it again (although Ronald does not like the LibreOffice dependency.)

Of course, now that there is much more of a maintenance impost with these gems, it is reasonable to ask @ronaldtse: is it worth putting this extra work into a gem we are no longer using?

**Comment by ronaldtse** [comment]
I actually think DOCX to AsciIDoc can't be that difficult. There are a number of Ruby DOCX parsers, and given that AsciiDoc is a "style-less" subset of DOCX syntax, it should be a straightforward conversion. 

Maybe @CAMOBAP795 would be interested? 😉

**Comment by CAMOBAP795** [comment]
> is it worth putting this extra work into a gem we are no longer using?

@opoudjis thanks for note, I think in this case it's really make no sense

> Maybe @CAMOBAP795 would be interested?

If we really need it, and there is no strict deadlines on it I can have a look, BTW in which part of `meranorma` this convertor will be used? Or it will be used just like standalone tool also?

**Comment by opoudjis** [comment]
Standalone; it is a tool used to convert existing DOCX documents into Asciidoctor on a one-off basis (with lots of post-editing cleanup), so that they can be fed into the Metanorma tool chain.

**Comment by CAMOBAP795** [comment]
> with lots of post-editing cleanup

@opoudjis correct me if I'm wrong: we cannot use existing tools like `pandoc`, just because of this post-editing cleanup, right?

**Comment by opoudjis** [comment]
@CAMOBAP795 I think Ronald is wrong, which is why I've refused to do it. :-)

The reverse_asciidoctor gem is based on reverse_markdown, and it presupposes a *very* clean HTML. Word HTML is very much not clean. The XSLT that is part of LibreOffice makes its output much cleaner.

A direct mapping of DOCX to Asciidoctor would be... 

... brave. I certainly am not interested in expending that amount of effort on it, when the mapping via LibreOffice HTML works. It does not work brilliantly, but it works well for something off the shelf.

**Comment by opoudjis** [comment]
Pandoc HTML is too strongly styled to be useful. I have not experimented with Pandoc DOCX > Asciidoctor since the very start of my involvement; and maybe it would produce acceptable output. If it doesn't deal with OMML > MathML, though, it's not useful.

Lots can go wrong in the mapping; Word HTML export, for example, does not preserve lists. You would want to review any DOCX > Asciidoctor conversion carefully, to make sure it preserves things such as footnotes, mathematical formatting, images (likely too hard), tables.

**Comment by CAMOBAP795** [comment]
@opoudjis thanks for the answer, 

@opoudjis @ronaldtse If everyone agrees I propose to close this task because of https://github.com/metanorma/omml2mathml/issues/6#issuecomment-481567737
